module.exports=[
             "Apple 15",
             "Apple 16",
             "Apple 17",
             "Samsung s10",
             "Samsung s11",
             "Samsung s12",
             "Samsung s13",
             "Samsung s14",
             "xeomi 10",
             "xeomi 11",
             "xeomi 12",
             "xeomi 13",
             "xeomi 14",
             "realme 2",
             "realme 3",
             "realme 4",
             "realme 5",
             "realme 6",
]